### ISSUE TITLE
Value should be a JSON object.

### ISSUE THREAD

**Issue by harikrish432** [DRN88/zabbix-playground#1]
I am getting this error in Zabbix dashboard 
 "Value should be a JSON object." 

Kindly help me with it.
![image](https://user-images.githubusercontent.com/32039646/49153289-52a58780-f33b-11e8-8671-b4ab1d2cd0e3.png)

**Comment by plouro** [comment]
Clone the git and cp them to externalscripts, if you Download the files the browser convert them to html.
